# Generated by Django 6.0.5 on 2026-06-02 09:15

import django.db.models.deletion
import uuid6
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0003_seed_admin'),
        ('crm', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentTransaction',
            fields=[
                ('identifier', models.UUIDField(default=uuid6.uuid7, editable=False, primary_key=True, serialize=False)),
                ('old_id', models.IntegerField(default=0)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('customer_email', models.EmailField(db_index=True, max_length=254)),
                ('stripe_payment_intent_id', models.CharField(blank=True, db_index=True, max_length=255, null=True, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('currency', models.CharField(default='usd', max_length=3)),
                ('provider', models.CharField(choices=[('stripe', 'Stripe'), ('flutterwave', 'Flutterwave')], max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('succeeded', 'Succeeded'), ('failed', 'Failed'), ('refunded', 'Refunded')], default='pending', max_length=20)),
                ('raw_data', models.JSONField(blank=True, default=dict)),
                ('synced_at', models.DateTimeField(blank=True, null=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_transactions', to='accounts.account')),
                ('deal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment_transactions', to='crm.deal')),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='PaymentProviderRecord',
            fields=[
                ('identifier', models.UUIDField(default=uuid6.uuid7, editable=False, primary_key=True, serialize=False)),
                ('old_id', models.IntegerField(default=0)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('provider_payment_id', models.CharField(max_length=255)),
                ('provider_status', models.CharField(max_length=50)),
                ('amount_charged', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('fee_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('webhook_payload', models.JSONField(blank=True, default=dict)),
                ('webhook_received_at', models.DateTimeField(blank=True, null=True)),
                ('transaction', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='provider_record', to='payments.paymenttransaction')),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='QueueJobRecord',
            fields=[
                ('identifier', models.UUIDField(default=uuid6.uuid7, editable=False, primary_key=True, serialize=False)),
                ('old_id', models.IntegerField(default=0)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('celery_task_id', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('processing', 'Processing'), ('done', 'Done'), ('failed', 'Failed')], default='queued', max_length=20)),
                ('retry_count', models.IntegerField(default=0)),
                ('last_error', models.TextField(blank=True)),
                ('enqueued_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='queue_jobs', to='payments.paymenttransaction')),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
    ]
