# Generated by Django 6.0.5 on 2026-06-02 09:09

import django.db.models.deletion
import uuid6
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0003_seed_admin'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('identifier', models.UUIDField(default=uuid6.uuid7, editable=False, primary_key=True, serialize=False)),
                ('old_id', models.IntegerField(default=0)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('hubspot_contact_id', models.CharField(db_index=True, max_length=64, unique=True)),
                ('email', models.EmailField(db_index=True, max_length=254)),
                ('first_name', models.CharField(blank=True, max_length=100)),
                ('last_name', models.CharField(blank=True, max_length=100)),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('lifecycle_stage', models.CharField(blank=True, max_length=50)),
                ('raw_properties', models.JSONField(blank=True, default=dict)),
                ('synced_at', models.DateTimeField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customers', to='accounts.account')),
            ],
            options={
                'ordering': ['last_name', 'first_name'],
            },
        ),
        migrations.CreateModel(
            name='HubspotOwner',
            fields=[
                ('identifier', models.UUIDField(default=uuid6.uuid7, editable=False, primary_key=True, serialize=False)),
                ('old_id', models.IntegerField(default=0)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('hubspot_owner_id', models.CharField(db_index=True, max_length=64, unique=True)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('first_name', models.CharField(blank=True, max_length=100)),
                ('last_name', models.CharField(blank=True, max_length=100)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hubspot_owners', to='accounts.account')),
            ],
            options={
                'ordering': ['last_name', 'first_name'],
            },
        ),
        migrations.CreateModel(
            name='Deal',
            fields=[
                ('identifier', models.UUIDField(default=uuid6.uuid7, editable=False, primary_key=True, serialize=False)),
                ('old_id', models.IntegerField(default=0)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('hubspot_deal_id', models.CharField(db_index=True, max_length=64, unique=True)),
                ('deal_name', models.CharField(max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('stage', models.CharField(choices=[('appointmentscheduled', 'Appointment Scheduled'), ('qualifiedtobuy', 'Qualified to Buy'), ('presentationscheduled', 'Presentation Scheduled'), ('decisionmakerboughtin', 'Decision Maker Bought In'), ('contractsent', 'Contract Sent'), ('closedwon', 'Closed Won'), ('closedlost', 'Closed Lost')], max_length=50)),
                ('closed_won_at', models.DateTimeField(blank=True, null=True)),
                ('expected_close_date', models.DateField(blank=True, null=True)),
                ('raw_properties', models.JSONField(blank=True, default=dict)),
                ('synced_at', models.DateTimeField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deals', to='accounts.account')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deals', to='crm.customer')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deals', to='crm.hubspotowner')),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
        migrations.AddField(
            model_name='customer',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customers', to='crm.hubspotowner'),
        ),
        migrations.CreateModel(
            name='HubspotSyncLog',
            fields=[
                ('identifier', models.UUIDField(default=uuid6.uuid7, editable=False, primary_key=True, serialize=False)),
                ('old_id', models.IntegerField(default=0)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('entity_type', models.CharField(choices=[('contact', 'Contact'), ('deal', 'Deal'), ('owner', 'Owner')], max_length=20)),
                ('sync_started_at', models.DateTimeField(blank=True, null=True)),
                ('sync_ended_at', models.DateTimeField(blank=True, null=True)),
                ('last_cursor', models.CharField(blank=True, max_length=255)),
                ('records_created', models.IntegerField(default=0)),
                ('records_updated', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('success', 'Success'), ('partial', 'Partial'), ('failed', 'Failed'), ('running', 'Running')], default='running', max_length=20)),
                ('error_message', models.TextField(blank=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hubspot_sync_logs', to='accounts.account')),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
    ]
