# Generated by Django 6.0.5 on 2026-06-02 09:18

import django.db.models.deletion
import uuid6
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0003_seed_admin'),
        ('crm', '0001_initial'),
        ('payments', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReconciliationRun',
            fields=[
                ('identifier', models.UUIDField(default=uuid6.uuid7, editable=False, primary_key=True, serialize=False)),
                ('old_id', models.IntegerField(default=0)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed')], default='running', max_length=20)),
                ('deals_processed', models.IntegerField(default=0)),
                ('transactions_processed', models.IntegerField(default=0)),
                ('anomalies_found', models.IntegerField(default=0)),
                ('triggered_by', models.CharField(default='scheduled', max_length=20)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reconciliation_runs', to='accounts.account')),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='Anomaly',
            fields=[
                ('identifier', models.UUIDField(default=uuid6.uuid7, editable=False, primary_key=True, serialize=False)),
                ('old_id', models.IntegerField(default=0)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('anomaly_type', models.CharField(choices=[('missing_payment', 'Missing Payment'), ('amount_mismatch', 'Amount Mismatch'), ('overpayment', 'Overpayment'), ('status_mismatch', 'Status Mismatch')], max_length=50)),
                ('severity', models.CharField(choices=[('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], default='medium', max_length=20)),
                ('expected_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('actual_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('expected_status', models.CharField(blank=True, max_length=50)),
                ('actual_status', models.CharField(blank=True, max_length=50)),
                ('description', models.TextField(blank=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anomalies', to='accounts.account')),
                ('deal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='anomalies', to='crm.deal')),
                ('payment_transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='anomalies', to='payments.paymenttransaction')),
                ('reconciliation_run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anomalies', to='reconciliation.reconciliationrun')),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='Resolution',
            fields=[
                ('identifier', models.UUIDField(default=uuid6.uuid7, editable=False, primary_key=True, serialize=False)),
                ('old_id', models.IntegerField(default=0)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('resolution_type', models.CharField(choices=[('adjust_deal', 'Adjust Deal'), ('refund', 'Refund'), ('manual_review', 'Manual Review'), ('ignore', 'Ignore')], max_length=50)),
                ('notes', models.TextField(blank=True)),
                ('resolved_at', models.DateTimeField(auto_now_add=True)),
                ('anomaly', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='resolution', to='reconciliation.anomaly')),
                ('resolved_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='resolved_anomalies', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
    ]
